### ISSUE TITLE
OTP geeft onmogelijke resultaten

### ISSUE THREAD

**Issue by basvank** [waagsociety/scholen#2]
@bertspaan We hebben alles inmiddels alles goed aan de praat en zijn een beetje aan het experimenteren met de software. Af en toe lopen we tegen dingen zoals de screenshot hieronder laat zien aan. Dat moet natuurlijk niet kunnen. Heb jij enig idee of dit een fout van OTP of de software is? En als het OTP is en ik daar en issue maak, snappen ze dan wat het probleem is of kan ik nog wat data uit het programma trekken om dit wat meer te onderbouwen?

![screenshot from 2015-01-21 12 06 03](https://cloud.githubusercontent.com/assets/2423870/5835221/3b0fa752-a166-11e4-86da-f084ca15c47c.png)

**Comment by bertspaan** [comment]
@basvank Ik heb dit soort dingen wel eerder gezien, maar nooit zo opvallend; het kan goed een interpolatiefout van OTPA zijn, of wellicht iets raars in de brondata (GTFS of OSM). Komt het vaak voor? En heb je meer voorbeelden van rare gevallen, die duidelijk niet kloppen?

**Comment by basvank** [comment]
Het komt wel vaker voor, als je gaat zoeken eens in de 10x ofzo, maar bijna nooit zo extreem als dit. Lopen is toch wel gewoon geactiveerd in OTPA? Of moet je dit als optie meegeven?

**Comment by bertspaan** [comment]
Volgens mij is lopen standaard geactiveerd, maar staat op max. tien minuten. In de normale OTP viewer (op localhost:poort/index.html) kun je dit aanpassen, maar hoe dit via de API moet weet ik niet uit m'n hoofd :expressionless:
