### ISSUE TITLE
OTP server on dev.opentripplanner.org

### ISSUE THREAD

**Issue by bertspaan** [waagsociety/scholen#4]
OTP with Amsterdam metropolitan region GTFS + OSM data should be available on dev.opentripplanner.org:
- https://s3.amazonaws.com/metro-extracts.mapzen.com/amsterdam_netherlands.osm.pbf
- http://gtfs.ovapi.nl/ns/gtfs-iffns-latest.zip
- http://gtfs.ovapi.nl/connexxion/gtfs-kv1connexxion-latest.zip
- http://gtfs.ovapi.nl/ebs/gtfs-kv1ebs-latest.zip
- http://gtfs.ovapi.nl/gvb/gtfs-kv1gvb-latest.zip

**Comment by abyrd** [comment]
I've got this working on port 9090. However I can't load the schools.geo.json, it looks like it hasn't been updated to match the new format in this repo.

**Comment by abyrd** [comment]
Ah, I see there are two copies of schools.geo.json in the repo, one in the root and one in otp/pointsets. I have copied over the newer one in the base of the repo (you might want to delete the old one). The new schools pointset is now available at http://dev.opentripplanner.org:9090/otp/pointsets/schools.geo
