### ISSUE TITLE
Use OTP URL params to set different transport modes

### ISSUE THREAD

**Issue by bertspaan** [waagsociety/scholen#6]
@abyrd: which URL params should I use to let the schools app set different transportation modes?

**Comment by abyrd** [comment]
Here are the API docs for the version we're running: http://dev.opentripplanner.org/apidoc/0.15.0/resource_SurfaceResource.html

The parameter you want is "mode", which takes a comma-separated list of modes. Common values are WALK, BICYCLE, CAR, TRAM, SUBWAY, RAIL, BUS, FERRY. The value TRANSIT activates all transit modes. The default is mode=WALK,TRANSIT.
