### ISSUE TITLE
OTP API should return travel time distance per school/pointset object

### ISSUE THREAD

**Issue by bertspaan** [waagsociety/scholen#8]
OTP API should return travel time distance per school/pointset object

**Comment by abyrd** [comment]
try adding the detail=true query parameter, it should return these values

**Comment by bertspaan** [comment]
:+1:

**Comment by bertspaan** [comment]
@abyrd in which query? I do not see the values in the `indicator` query:
http://dev.opentripplanner.org:9090/otp/surfaces/67/indicator?targets=schools.geo&detail=true
Output:
https://gist.github.com/anonymous/6f755de59c8bff175ef6

**Comment by abyrd** [comment]
Rest assured that with detail=true you are indeed constructing an object containing all the detailed travel times on the server... but unfortunately I just discovered that the serialization code does not know that, and doesn't write out the array of times. It's a simple fix, but one that will have repercussions on other systems so I can't fix it immediately.

**Comment by bertspaan** [comment]
Ok, thanks for letting me know. It's not too important, we can do without the exact travel time per school. 

You can see http://code.waag.org/scholen/ for the latest version, I'll need a couple of hours to finish it.
